from lib import *

estudiante_1 = estudianteGraduado(601049, "ACOSTA ZAIRA", 35)
estudiante_1.setCalificacion(int(10))
estudiante_1.setCalificacion(int(9))
estudiante_1.setCalificacion(int(8))
estudiante_1.setCalificacion(int(7))
estudiante_1.setCalificacion(int(6))
estudiante_1.setFecha("2021-06-01")
estudiante_1.setTesis("Los neutrinos saben a jugo de uva")

estudiante_2 = estudianteGraduado(601048, "DURÁN FRINE", 34)
estudiante_2.setCalificacion(int(6))
estudiante_2.setCalificacion(int(5))
estudiante_2.setCalificacion(int(5))
estudiante_2.setCalificacion(int(4))
estudiante_2.setCalificacion(int(3))

estudiante_3 = estudianteGraduado(100738, "GARCIA VICTOR", 20)
estudiante_3.setCalificacion(int(8))
estudiante_3.setCalificacion(int(3))
estudiante_3.setCalificacion(int(4))
estudiante_3.setCalificacion(int(5))
estudiante_3.setCalificacion(int(4))

estudiante_4 = estudianteGraduado(100744, "LOPEZ DIEGO", 20)
estudiante_4.setCalificacion(int(10))
estudiante_4.setCalificacion(int(9))
estudiante_4.setCalificacion(int(8))
estudiante_4.setCalificacion(int(10))
estudiante_4.setCalificacion(int(8))
estudiante_4.setFecha("2026-05-01")
estudiante_4.setTesis("Los efectos de la pandemia en la educación")

estudiante_5 = estudianteGraduado(100692, "LOPEZ EVELYN", 20)
estudiante_5.setCalificacion(int(10))
estudiante_5.setCalificacion(int(8))
estudiante_5.setCalificacion(int(9))
estudiante_5.setCalificacion(int(5))
estudiante_5.setCalificacion(int(9))
estudiante_5.setFecha("2027-05-01")
estudiante_5.setTesis("Riesgos de personal de salud en la pandemia")

estudiante_6 = estudianteGraduado(999999, "ROJAS DANIEL", 20)
estudiante_6.setCalificacion(int(6))
estudiante_6.setCalificacion(int(5))
estudiante_6.setCalificacion(int(4))
estudiante_6.setCalificacion(int(4))
estudiante_6.setCalificacion(int(3))

estudiante_7 = estudianteGraduado(100870, "ROSAS MAURIZIO", 20)
estudiante_7.setCalificacion(int(10))
estudiante_7.setCalificacion(int(6))
estudiante_7.setCalificacion(int(10))
estudiante_7.setCalificacion(int(9))
estudiante_7.setCalificacion(int(8))
estudiante_7.setFecha("2026-08-01")
estudiante_7.setTesis("Estadisticas de los videojuegos en la pandemia")

estudiante_8 = estudianteGraduado(100437, "VILLEGAS ANNIBAL", 20)
estudiante_8.setCalificacion(int(10))
estudiante_8.setCalificacion(int(9))
estudiante_8.setCalificacion(int(8))
estudiante_8.setCalificacion(int(7))
estudiante_8.setCalificacion(int(6))
estudiante_8.setFecha("2026-12-01")
estudiante_8.setTesis("Porque el Cruz Azul no gana la liga")


print("")
print("\033[46mCalificaciones de los estudiantes de actuaria UTECA\033[0m")
print("")
print("                                  |  Calificaciones  |")
print("Matricula| Nombre           | Edad| 1  | 2 | 3  | 4  | 5 |Final|Grad?| Fecha      | Tesis")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_1.matricula}   | \033[1m{estudiante_1.apellidoNombre}\033[0m     | {estudiante_1.edad}  | {estudiante_1.calificacion[0]} | {estudiante_1.calificacion[1]} | {estudiante_1.calificacion[2]}  | {estudiante_1.calificacion[3]}  | {estudiante_1.calificacion[4]} | {estudiante_1.promedio()} | {str(estudiante_1.chkGrad())}  | {estudiante_1.chckFecha()} | {estudiante_1.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_2.matricula}   | \033[1m{estudiante_2.apellidoNombre}\033[0m      | {estudiante_2.edad}  | {estudiante_2.calificacion[0]}  | \033[31m{estudiante_2.calificacion[1]}\033[0m | \033[31m{estudiante_2.calificacion[2]}\033[0m  | \033[31m{estudiante_2.calificacion[3]}\033[0m  | \033[31m{estudiante_2.calificacion[4]}\033[0m | \033[41m{estudiante_2.promedio()}\033[0m | {str(estudiante_2.chkGrad())}  | {estudiante_2.chckFecha()}        | {estudiante_2.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_3.matricula}   | \033[1m{estudiante_3.apellidoNombre}\033[0m    | {estudiante_3.edad}  | {estudiante_3.calificacion[0]}  | \033[31m{estudiante_3.calificacion[1]}\033[0m | \033[31m{estudiante_3.calificacion[2]}\033[0m  | \033[31m{estudiante_3.calificacion[3]}\033[0m  | \033[31m{estudiante_3.calificacion[4]}\033[0m | \033[41m{estudiante_3.promedio()}\033[0m | {str(estudiante_3.chkGrad())}  | {estudiante_3.chckFecha()}        | {estudiante_3.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_4.matricula}   | \033[1m{estudiante_4.apellidoNombre}\033[0m      | {estudiante_4.edad}  | {estudiante_4.calificacion[0]} | {estudiante_4.calificacion[1]} | {estudiante_4.calificacion[2]}  | {estudiante_4.calificacion[3]} | {estudiante_4.calificacion[4]} | {estudiante_4.promedio()} | {str(estudiante_4.chkGrad())}  | {estudiante_4.chckFecha()} | {estudiante_4.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_5.matricula}   | \033[1m{estudiante_5.apellidoNombre}\033[0m     | {estudiante_5.edad}  | {estudiante_5.calificacion[0]} | {estudiante_5.calificacion[1]} | {estudiante_5.calificacion[2]}  | \033[31m{estudiante_5.calificacion[3]}\033[0m  | {estudiante_5.calificacion[4]} | {estudiante_5.promedio()} | {str(estudiante_5.chkGrad())}  | {estudiante_5.chckFecha()} | {estudiante_5.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_6.matricula}   | \033[1m{estudiante_6.apellidoNombre}\033[0m     | {estudiante_6.edad}  | {estudiante_6.calificacion[0]}  | \033[31m{estudiante_6.calificacion[1]}\033[0m | \033[31m{estudiante_6.calificacion[2]}\033[0m  | \033[31m{estudiante_6.calificacion[3]}\033[0m  | \033[31m{estudiante_6.calificacion[4]}\033[0m | \033[41m{estudiante_6.promedio()}\033[0m | {str(estudiante_6.chkGrad())}  | {estudiante_6.chckFecha()}        | {estudiante_6.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_7.matricula}   | \033[1m{estudiante_7.apellidoNombre}\033[0m   | {estudiante_7.edad}  | {estudiante_7.calificacion[0]} | {estudiante_7.calificacion[1]} | {estudiante_7.calificacion[2]} | {estudiante_7.calificacion[3]}  | {estudiante_7.calificacion[4]} | {estudiante_7.promedio()} | {str(estudiante_7.chkGrad())}  | {estudiante_7.chckFecha()} | {estudiante_7.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(f"{estudiante_8.matricula}   | \033[1m{estudiante_8.apellidoNombre}\033[0m | {estudiante_8.edad}  | {estudiante_8.calificacion[0]} | {estudiante_8.calificacion[1]} | {estudiante_8.calificacion[2]}  | {estudiante_8.calificacion[3]}  | {estudiante_8.calificacion[4]} | {estudiante_8.promedio()} | {str(estudiante_8.chkGrad())}  | {estudiante_8.chckFecha()} | {estudiante_8.chckTesis()}")
print("-------------------------------------------------------------------------------------------------------------------------------------")
print("")
print("\033[45mDatos estudiantes de actuaria UTECA\033[0m")
print("")
print(estudiante_1)
print(estudiante_2)
print(estudiante_3)
print(estudiante_4)
print(estudiante_5)
print(estudiante_6)
print(estudiante_7)
print(estudiante_8)